[package]
name = "oxc_utils"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf   = { workspace = true, features = ["macros"] }
convert_case    = { workspace = true }
oxc_syntax      = { workspace = true }
oxc_span        = { workspace = true }

[lints]
workspace = true
